### PR TITLE
Added reliability logs

### PR DESCRIPTION
**Pull request by rudibravo**
Added logs to bigquery. Those are going to count toward our reliability.
I tested it on my display by revoking the credentials and verified it logged correctly:
https://bigquery.cloud.google.com/results/client-side-events:US.bquijob_f56419d_163406602e5

@Rise-Vision/content please review.

### CODE REVIEW

**Comment by jungeunyoon** [comment]
@rudibravo Any reason why you're not using the [`error`](https://github.com/Rise-Vision/twitter-module/blob/master/src/logger.js#L23) function?

**Comment by rudibravo** [comment]
@jungeunyoon I want those logs to be on bigquery. I might have misunderstood the API.

**Comment by jungeunyoon** [comment]
@rudibravo `error` logs to BQ --> [see end function here](https://github.com/Rise-Vision/rise-common-electron/blob/master/logger.js#L91)

**Comment by rudibravo** [comment]
@jungeunyoon thanks. I will change it to use error and also change the error log message slightly.

**Comment by jungeunyoon** [comment]
@rudibravo sounds good, thanks! 👍

**Comment by rudibravo** [comment]
@jungeunyoon I've changed it to use `error` and removed the `file`, since it's already called inside `error`.

**Pull request merged**
